package test

import (
	_ "embed"
)

// BinExampleAuth was generated by the following:
//
//	cd testdata/examples; wat2wasm --debug-names auth.wat
//
//go:embed testdata/examples/auth.wasm
var BinExampleAuth []byte

// BinExampleConfig was generated by the following:
//
//	cd testdata/examples; wat2wasm --debug-names config.wat
//
//go:embed testdata/examples/config.wasm
var BinExampleConfig []byte

// BinExampleLog was generated by the following:
//
//	cd testdata/examples; wat2wasm --debug-names log.wat
//
//go:embed testdata/examples/log.wasm
var BinExampleLog []byte

// BinExampleRouter was generated by the following:
//
//	cd testdata/examples; wat2wasm --debug-names router.wat
//
//go:embed testdata/examples/router.wasm
var BinExampleRouter []byte

// BinExampleRedact was generated by the following:
//
//	cd testdata/examples; wat2wasm --debug-names redact.wat
//
//go:embed testdata/examples/redact.wasm
var BinExampleRedact []byte

// BinTestProtocolVersion was generated by the following:
//
//	cd testdata/examplestests; wat2wasm --debug-names protocol_version.wat
//
//go:embed testdata/tests/protocol_version.wasm
var BinTestProtocolVersion []byte
