package wasm

import (
	"context"
	_ "embed"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/httptest"

	httpwasm "github.com/http-wasm/http-wasm-host-go"
)

// authWasm was generated by the following:
//
//	cd testdata; wat2wasm --debug-names auth.wat
//
//go:embed testdata/auth.wasm
var authWasm []byte

// logWasm was generated by the following:
//
//	cd testdata; wat2wasm --debug-names log.wat
//
//go:embed testdata/log.wasm
var logWasm []byte

func Example_auth() {
	ctx := context.Background()

	// Configure and compile the WebAssembly guest binary. In this case, it is
	// an auth interceptor.
	mw, err := NewMiddleware(ctx, authWasm)
	if err != nil {
		log.Panicln(err)
	}
	defer mw.Close(ctx)

	// Create the real request handler.
	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		w.Write([]byte("{\"hello\": \"world\"}")) // nolint
	})

	// Wrap this with an interceptor implemented in WebAssembly.
	wrapped, err := mw.NewHandler(ctx, next)
	if err != nil {
		log.Panicln(err)
	}

	// Start the server with the wrapped handler.
	ts := httptest.NewServer(wrapped)
	defer ts.Close()

	// Invoke some requests, only one of which should pass
	headers := []http.Header{
		{"NotAuthorization": {"1"}},
		{"Authorization": {""}},
		{"Authorization": {"1"}},
		{"Authorization": {"0"}},
	}

	for _, header := range headers {
		req, err := http.NewRequest(http.MethodGet, ts.URL, nil)
		if err != nil {
			log.Panicln(err)
		}
		req.Header = header

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			log.Panicln(err)
		}
		resp.Body.Close()

		switch resp.StatusCode {
		case http.StatusOK:
			fmt.Println("OK")
		case http.StatusUnauthorized:
			fmt.Println("Unauthorized")
		default:
			log.Panicln("unexpected status code", resp.StatusCode)
		}
	}

	// Output:
	// Unauthorized
	// Unauthorized
	// OK
	// Unauthorized
}

func Example_log() {
	ctx := context.Background()
	logger := httpwasm.Logger(func(msg string) { fmt.Println(msg) })

	// Configure and compile the WebAssembly guest binary. In this case, it is
	// a logging interceptor.
	mw, err := NewMiddleware(ctx, logWasm, Logger(logger))
	if err != nil {
		log.Panicln(err)
	}
	defer mw.Close(ctx)

	// Create the real request handler.
	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		w.Write([]byte("{\"hello\": \"world\"}")) // nolint
	})

	// Wrap this with an interceptor implemented in WebAssembly.
	wrapped, err := mw.NewHandler(ctx, next)
	if err != nil {
		log.Panicln(err)
	}

	// Start the server with the wrapped handler.
	ts := httptest.NewServer(wrapped)
	defer ts.Close()

	// Make a client request and print the contents to the same logger
	resp, err := http.Get(ts.URL)
	if err != nil {
		log.Panicln(err)
	}
	defer resp.Body.Close()
	content, _ := io.ReadAll(resp.Body)
	logger(string(content))

	// Output:
	// before
	// after
	// {"hello": "world"}
}
